<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Suites</title>

    <!-- Font Awesome icons -->
    <script src="https://kit.fontawesome.com/f9ece565b9.js" crossorigin="anonymous"></script>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Arimo&display=swap%27" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Arimo&family=Bebas+Neue&display=swap%27" rel="stylesheet">
    <link href="../assets/styles/suites.css" rel="stylesheet">
    <link rel="stylesheet" href="../assets/styles/header.css">
</head>
<body>
<?php
    require_once('../components/header.php');
?>
<div class="container-fluid d-flex align-items-center min-vh-100 spaceBackground">
<div class="row row-cols-1">
    <div class="col-md-12 p-3 bg-white">
        <h1>Available Suites</h1>
        <div class="suite-dates">
            <form action="<?php echo $_SERVER['PHP_SELF'];?>" method="post">
            <label>
                Date From
                <input type="date" id="date-from" name="date-from" required value="<?php echo  $_POST['date-from'] ?? "2021-01-01"?>">
            </label>
            <label>
                Date To
                <input type="date" id="date-to" name="date-to" required value="<?php echo $_POST['date-to'] ?? "2021-01-01" ?>">
            </label>
            <input type="submit" value="Zoeken">
            </form>
        </div>
    </div>
    <div class="col-md-12 p-3 bg-white">
        <!-- coordinates found with https://www.image-map.net/ -->
        <svg width="400" height="400">
                <polygon onclick="showSuite()" points="198,128 199,5 171,7 141,14 121,22 97,33 78,48 61,61 49,75 38,89 30,101 26,109 132,170 139,158 149,147 161,139 173,133 185,130"
                    style="fill:lime;stroke:black;stroke-width:1;fill-rule:evenodd;" />
            <polygon points="199,6 198,128 210,130 223,133 235,139 245,146 251,151 257,158 261,163 265,168 375,118 364,96 353,80 335,60 315,43 293,29 269,18 248,11 223,7"
                style="fill:lime;stroke:black;stroke-width:1;fill-rule:evenodd;" />
            <polygon points="375,117 384,140 391,174 393,200 391,226 388,244 381,266 373,284 364,300 354,314 347,324 335,335 251,250 262,236 269,221 272,204 271,184 265,168"
                style="fill:lime;stroke:black;stroke-width:1;fill-rule:evenodd;" />
            <polygon points="151,256 76,348 93,361 116,373 140,383 167,389 196,392 230,390 253,384 288,371 305,360 320,349 335,335 251,250 240,258 225,266 210,270 196,272 184,270 170,265 160,261"
                style="fill:lime;stroke:black;stroke-width:1;fill-rule:evenodd;" />
            <polygon points="25,109 132,169 126,188 125,204 129,222 135,236 143,247 151,256 76,349 50,325 35,304 24,282 15,262 7,231 4,207 4,184 9,157 15,135"
                style="fill:lime;stroke:black;stroke-width:1;fill-rule:evenodd;" />
            <circle cx="200" cy="199" r="38"
                style="fill:lime;stroke:black;stroke-width:1;fill-rule:evenodd;" />
        </svg>
        <!-- <img src="../assets/img/Suites.png" alt="map of suites" usemap="#suiteSelect" height="400px"> -->
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <!-- <img src="Suites.png" usemap="#image-map"> -->

        <!-- <map name="image-map">
            <area target="" alt="" title="" href="" coords="198,128,199,5,171,7,141,14,121,22,97,33,78,48,61,61,49,75,38,89,30,101,26,109,132,170,139,158,149,147,161,139,173,133,185,130" shape="poly">
            <area target="" alt="" title="" href="" coords="199,6,198,128,210,130,223,133,235,139,245,146,251,151,257,158,261,163,265,168,375,118,364,96,353,80,335,60,315,43,293,29,269,18,248,11,223,7" shape="poly">
            <area target="" alt="" title="" href="" coords="375,117,384,140,391,174,393,200,391,226,388,244,381,266,373,284,364,300,354,314,347,324,335,335,251,250,262,236,269,221,272,204,271,184,265,168" shape="poly">
            <area target="" alt="" title="" href="" coords="151,256,76,348,93,361,116,373,140,383,167,389,196,392,230,390,253,384,288,371,305,360,320,349,335,335,251,250,240,258,225,266,210,270,196,272,184,270,170,265,160,261" shape="poly">
            <area target="" alt="" title="" href="" coords="25,109,132,169,126,188,125,204,129,222,135,236,143,247,151,256,76,349,50,325,35,304,24,282,15,262,7,231,4,207,4,184,9,157,15,135" shape="poly">
            <area target="" alt="" title="" href="" coords="200,199,38" shape="circle">
        </map> -->
    </div>
</div>
    <?php
    include_once "../controllers/database/dbconnect.php";
    include_once "../controllers/database/reservation-db-functions.php";
    $startDate = filter_input(INPUT_POST, 'date-from', FILTER_SANITIZE_STRING, array('options' => array('default' => "2021-01-01")));
    $endDate = filter_input(INPUT_POST, 'date-to', FILTER_SANITIZE_STRING, array('options' => array('default' => "2021-01-01")));

    if(!strtotime($startDate) || !strtotime($endDate)){
        die("Invalid date.");
    }

    $suites = getFreeSuites($startDate, $endDate);
    if(empty($suites)){
        // echo "No available suites";
    } else {
    foreach ($suites as $suite) { ?>
        <div class="suite">
            <?php
            $dirPath = "../assets/img/suites/" . $suite['ID'] . "/";
            if (!file_exists($dirPath)) {
                mkdir($dirPath);
            }

            $photos = scandir($dirPath);
            $photoPath = "../assets/img/suites/placeholder.png";
            foreach ($photos as $photo) {
                $path = $dirPath . $photo;
                if (!isImage($path)) {
                    continue;
                }
                $photoPath = $path;
                break;
            }
            echo "<div class='suite-image'><img src='" . $photoPath . "' alt='" . $suite['name']  . "'></div>";
            ?>
            <div class="suite-text">
                <h2 style="display: inline-block"><a href="suite.php?id=<?php echo $suite['ID'] ?>">
                        <?php echo $suite['name']  ?></a></h2>
                <div class="suite-details">
                    Size: <?php echo $suite['suite_size']?>
                    Rooms: <?php echo $suite['rooms'] ?>
                </div>
                <p><?php echo $suite['description'] ?></p>
                <div class="suite-price">Price: &dollar;<?php echo $suite['price']?></div>
            </div>
        </div>

    <?php }
    }

    function isImage($path): bool {
        if (@is_array(getimagesize($path))) {
            $image = true;
        } else {
            $image = false;
        }
        return $image;
    }

    ?>
    <script>
        function showSuite($suiteId){
            
        }
    </script>
</div>
</body>
</html>